global using Xunit;
global using Api.Mutations;
global using Api.UnitTests.Shared;
global using Api.Utilities;
global using AutoFixture;
global using HotChocolate;
global using Infra.MongoDb.Repositories.UsersTechnology;
global using NSubstitute;
global using Shared.Domain.Entities;